sudo: required
language: go
go:
- '1.14'
env:
- CHANGE_MINIKUBE_NONE_USER=true
services:
  - docker
before_script:
- curl -Lo kubectl https://storage.googleapis.com/kubernetes-release/release/https://storage.googleapis.com/kubernetes-release/release/v1.15.9/bin/linux/amd64/kubectl/bin/linux/amd64/kubectl
- chmod +x kubectl
- sudo mv kubectl /usr/local/bin/
- curl -Lo minikube https://storage.googleapis.com/minikube/releases/v1.9.2/minikube-linux-amd64
- chmod +x minikube
- sudo mv minikube /usr/local/bin/
- sudo minikube start --vm-driver=none --kubernetes-version=v1.15.9
- minikube update-context
- until kubectl get nodes | grep -i master | grep -i ready; do sleep 1; done
script:
  - make test
  - make build
