---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: relay-frontend
  labels:
    app: relay-frontend
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
        maxSurge: 50%
        maxUnavailable: 0%
  selector:
    matchLabels:
      app: relay-frontend
  template:
    metadata:
      labels:
        app: relay-frontend
    spec:
      containers:
      - name: relay-frontend
        image: firefoxx04/relay-frontend:latest
        ports:
        - containerPort: 8080
          name: http
        env:
        - name: RELAY_LOG_LEVEL
          value: trace
        - name: RELAY_PROJECT_ID
          value: someproject
        command: ["/relay/frontend"]
        args: ["-topic=test"]
        resources:
          requests:
            cpu: 1m
        livenessProbe:
          httpGet:
            path: /status
            port: 8080
          initialDelaySeconds: 2
          periodSeconds: 3
        readinessProbe:
          httpGet:
            path: /status
            port: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: relay-frontend
spec:
  type: ClusterIP
  ports:
  - name: http
    targetPort: http
    port: 8080
  selector:
    app: relay-frontend
